---
name: Lint

#############################
# Start the job on push     #
#############################
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Run ESLint, Prettier, and TypeScript compiler
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Install packages             #
      ################################
      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      ################################
      # Lint codebase                #
      ################################
      - name: Run ESLint
        run: pnpm exec eslint .

      ################################
      # Check Prettier on codebase   #
      ################################
      - name: Run Prettier
        run: pnpm exec prettier --check .

      ################################
      # Check for TypeScript errors  #
      ################################
      - name: Run TypeScript compiler (tsc)
        run: pnpm exec tsc --noEmit